FORMAT: 1A
HOST: https://api.example.com

# My API Documentation
This is an API template for reference purposes only.

# Group common
<!-- include(bin/common/error.apib) -->
<!-- include(bin/common/pagination.apib) -->
<!-- include(bin/common/sort.apib) -->
<!-- include(bin/common/filter.apib) -->
<!-- include(bin/common/message.apib) -->

# Group Product
<!-- include(bin/product/productList.apib) -->